### ISSUE TITLE
Windows 10 Mobile support

### ISSUE THREAD

**Issue by valentinoli** [pwa-builder/pwabuilder-windows-chromium-docs#2]
I am curious to know why [the docs](https://github.com/pwa-builder/pwabuilder-windows-chromium-docs/blob/master/publish-new-app.md#add-packages) suggest to only check the "Windows 10 Desktop" checkbox. Why is the generated package not supported on Windows 10 mobile, for instance, even though the submission site seems to suggest it is supported. Here is how I left my submission, before I found these helpful docs.

![image](https://user-images.githubusercontent.com/23453691/99791588-1c640280-2b26-11eb-814d-9521f0210601.png)

**Comment by davrous** [comment]
The Chromium-based Edge won't be backported to Windows 10 Mobile, which is not supported anymore. That's why you shouldn't try to target something else than Windows 10 Desktop for now as the other platform simply won't work.
