### ISSUE TITLE
pwabuilder install.ps1 script doesn't work with Chinese app name.

### ISSUE THREAD

**Issue by MrMYHuang** [pwa-builder/pwabuilder-windows-chromium-docs#3]
I used https://www.pwabuilder.com/ to package my PWA app for publishing to Windows Store. However, I find the generated **install.ps1** script doesn't work with Chinese app name as specified in this screen shot:
![image](https://user-images.githubusercontent.com/12458706/100098359-e792db00-2e98-11eb-96b4-347bac9b94fa.png)

A workaround is to replace all Chinese names with an English names in the generated archive:
* Replace all Chinese names in **install.ps1** script with an English name, e.g., "abc."
* Rename filenames with extensions msixbundle and classic.appxbundle to abc.msixbundle and abc.classic.appxbundle.
* Run **install.ps1**.

**Comment by davrous** [comment]
Thanks for your feedback. We may have a unicode issue. Pinging @JudahGabriel

**Comment by valentinoli** [comment]
I experienced a similar issue. Solved it by editing the reference to the bundle in the `install.ps1`

**Comment by JudahGabriel** [comment]
Thanks! I see Powershell is misinterpreting the command when the app name has unicode characters in it. I'm investigating and should have a fix for this tomorrow.

**Comment by JudahGabriel** [comment]
I'm glad to report that this issue is now fixed; the install script properly uses the right encoding, and I was able to successfully install an app with a Chinese name.
