### ISSUE TITLE
Change package language

### ISSUE THREAD

**Issue by valentinoli** [pwa-builder/pwabuilder-windows-chromium-docs#4]
I could not find out how to change the language supported by the package. The default language I got was English (United States). In my case the PWA is not in English. Does anyone know how to change that? I tried setting the `lang` property in the app manifest, but that didn't work.

**Comment by JudahGabriel** [comment]
I don't think this is supported, currently. Investigating...

**Comment by JudahGabriel** [comment]
@valentinoli Currently, PWABuilder will generate app packages with the following AppxManifest.xml:

```xml
<Resources>
   <Resource Language="EN-US"/>
</Resources>
```

We can trivially extend PWABuilder to generate packages with a different language. But let me first understand, what are you looking to do? Provide different translations of your UI to users? Or something else?

**Comment by valentinoli** [comment]
@JudahGabriel

My app is only provided in Icelandic so naturally I want users to see that language in the "Supported languages" section of the Microsoft Store listing, and not English (United States).

See top of the following screenshot:

![Screenshot_20201201-094610.png](https://user-images.githubusercontent.com/23453691/100717414-49cc6e00-33ba-11eb-8719-4db1d2813d4d.png)

**Comment by valentinoli** [comment]
@JudahGabriel have you looked into this? Could the language be extracted from the `manifest.json` or else given the default English (United States) if not provided? Or would you rather allow the user to choose another language in the pwabuilder.com dialog?

**Comment by JudahGabriel** [comment]
After talking with our tooling team, yeah, we can do this. We've created the work item to enable it and is now in review. Once the tooling is updated, we'll push a UI update to allow language selection, and populate it by default with the language from the web manifest. 

Thanks for bringing this to our attention!

**Comment by valentinoli** [comment]
Ah, that's awesome. Thanks for the update :)

**Comment by JudahGabriel** [comment]
Our internal tooling has been updated to support this. I've now got [this PR opened](https://github.com/pwa-builder/PWABuilder/pull/1448) to enable UI support in PWABuilder to change the language of the app package.

**Comment by JudahGabriel** [comment]
This has now been deployed to our [preview environment](https://preview.pwabuilder.com):

![image](https://user-images.githubusercontent.com/312936/107448661-f5024d80-6af6-11eb-8803-5544351d6c29.png)

We will likely roll out to production within the week.

**Comment by JudahGabriel** [comment]
This has been rolled out to production.
