### ISSUE TITLE
UWP packages are created, but it doesn't work!

### ISSUE THREAD

**Issue by shahramSo** [pwa-builder/pwabuilder-windows-chromium-docs#5]
I created UWP packages as your documentation and I have run install.ps1 under "Run with PowerShell" but it doesn't work and also
I didn't see any error, and I didn't see my app in the Start Menu.
For more testing, I created a UWP package of your app "PWABuilder" but the result was same;
I have changed the "Set-ExecutionPolicy bypass" by PowerShell but it doesn't work.
I think that there is a issue in the code of install file to find path of target package.
Finally, all packages are created but there is no way to test it before submitting to the Store.
My OS Machine is win 10 Pro.
Thanks

**Comment by JudahGabriel** [comment]
Hey @shahramSo

> I have changed the "Set-ExecutionPolicy bypass" by PowerShell but it doesn't work

What error are you receiving?

p.s. please open issues on our [main GitHub repo](https://github.com/pwa-builder/pwabuilder/issues).
