### ISSUE TITLE
Are app shortcuts supported?

### ISSUE THREAD

**Issue by valentinoli** [pwa-builder/pwabuilder-windows-chromium-docs#6]
I see that when I install my PWA to my homescreen from the new Edge, app shortcuts are available when I right click the icon. But when I install it from Microsoft Store, they are not available. 

[App shortcuts](https://web.dev/app-shortcuts/)

**Comment by JudahGabriel** [comment]
Hey @valentinoli 

I'm noticing that too, though it had been working previously. I'll check with the Edge team and see what's going on.

**Comment by JudahGabriel** [comment]
We're investigating this and tracking it internally. I'll update here when we have more info.

**Comment by JudahGabriel** [comment]
We've found the source of the problem. It'll be fixed when Edge 90 rolls out. We're considering back-porting the fix to Edge 88 and 89. I'll keep you abreast of updates on this.

**Comment by valentinoli** [comment]
Excellent news, thanks for the update!

**Comment by JudahGabriel** [comment]
Hey @valentinoli 

Good news: Edge 90 rolled out yesterday, and I'm glad to report that shortcuts are working once again. Here's my Store PWA with its shortcuts:

![image](https://user-images.githubusercontent.com/312936/115059495-7c739080-9e9b-11eb-8b62-16ca89379f0b.png)

**Comment by valentinoli** [comment]
Yes, it works! Awesome :)
