### ISSUE TITLE
Why minWindowsVersion is 10.0.19041?

### ISSUE THREAD

**Issue by khmyznikov** [pwa-builder/pwabuilder-windows-chromium-docs#7]
So, it's minimal for local testing or even for installing from store?

**Comment by JudahGabriel** [comment]
Please see https://github.com/pwa-builder/pwabuilder-windows-chromium-docs/blob/master/classic-package.md

In particular, we offer you two packages. The first package works on versions 10.0.19041 and newer. The reason for that is, it utilizes the new Hosted App model that was offered in that version of Windows.

We also offer you a classic app package that you should publish as well. This doesn't use the new hosted app model, so it runs on older versions of Windows. It will be offered to users installing your app who are running older versions of Windows.
